title: "Материалы для доклада"
description: "Репозиторий с материалами лекций"

# GitHub Pages settings
markdown: kramdown
highlighter: rouge
theme: minima

# Math support
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap 