title: "Доклады и материалы по тематике LLM"
description: "Материалы для докладов Феоктистова Станислава на YouTube канале 'Клуб Разработчиков СПб'"

# GitHub Pages settings  
baseurl: "/materials-from-lectures" # название репозитория
url: "https://bbar0n234.github.io" # замените на ваш GitHub username
markdown: kramdown
highlighter: rouge
theme: minima

# Custom color theme (for minima 2.5)
# Available options: default, dark, blue, green
color_theme: default

# Math support
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed

# Allow documents with a future date to be published locally, so lecture previews appear
future: true

collections:
  lectures:
    output: true
    permalink: /:collection/:name/
  notes:
    output: true
    permalink: /:collection/:name/
  links:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "notes"
  - scope:
      path: ""
      type: "links"
    values:
      layout: "link" 